- hosts: localhost
  gather_facts: no
  connection: local
  environment:
    GHQ_ROOT: /Users/{{ ansible_ssh_user }}/dev/src
    GOPATH: /Users/{{ ansible_ssh_user }}/dev/go
  tasks:
    - name: install homebrew packages
      homebrew:
        name: '{{ item }}'
      with_items:
        - ghq
        - vim
        - zsh
    - name: get dotfiles
      shell: ghq get https://github.com/motemen/dotfiles
      args:
        creates: ~/dev/src/github.com/motemen/dotfiles/.git
    - name: setup dotfiles
      shell: ~/dev/src/github.com/motemen/dotfiles/setup
      args:
        creates: /Users/{{ ansible_ssh_user }}/.zshrc
    - name: tap homebrew taps
      homebrew_tap:
        name: '{{ item }}'
      with_items:
        - homebrew/versions
    - name: install homebrew packages
      homebrew:
        name: '{{ item }}'
      with_items:
        - checkbashisms
        - coreutils
        - ctags
        - docker
        - docker-compose
        - docker-machine
        - entr
        - envchain
        - fzf
        - ghi
        - git
        - go
        - heroku-toolbelt
        - highlight
        - httpie
        - hub
        - jq
        - keychain
        - less
        - mercurial
        - node
        - pass
        - plenv
        - perl-build
        - pstree
        - pt
        - pup
        - rainbarf
        - rbenv
        - reattach-to-user-namespace
        - sbt
        - shellcheck
        - tig
        - tmux
        - tree
        - w3m
        - postgresql
        - redis
    - name: mkdir ~/bin
      file:
        state: directory
        path: ~/bin
    - name: install git-contrib tools
      shell: |
        cp $(brew --prefix git)/share/git-core/contrib/{{ item }}/{{ item }} ~/bin && \
        chmod +x ~/bin/{{ item }}
      args:
        creates: ~/bin/{{ item }}
      with_items:
        - diff-highlight
        - git-jump
    - name: install go-provided tools
      shell: go get -v {{ item }}
      args:
        creates: ~/dev/go/bin/{{ item | basename }}
      with_items:
        - github.com/golang/lint/golint
        - github.com/jstemmer/gotags
        - github.com/motemen/ghq
        - github.com/motemen/github-commit-status-mark
        - github.com/motemen/go-iferr/cmd/goiferr
        - github.com/motemen/go-quickfix/cmd/goquickfix
        - github.com/motemen/go-typeswitch-gen/cmd/tsgen
        - github.com/motemen/gore
        - github.com/motemen/hub-pr
        - github.com/nsf/gocode
        - golang.org/x/tools/cmd/goimports
        - github.com/constabulary/gb/...
#   - name: install gem-provided tools
#     shell: |
#       gem install {{ item }}
#       echo "RBENV_VERSION=$RBENV_VERSION {{ item }}" > ~/bin/{{ item }}
#       chmod +x ~/bin/{{ item }}
#     environment:
#       RBENV_VERSION: 2.2.4
#     with_items:
#       - git-browse-remote
    - name: install homebrew cask packages
      homebrew_cask:
        name: '{{ item }}'
      with_items:
        - 1password
        - android-studio
        - dropbox
        - firefox
        - flux
        - google-chrome
        - google-japanese-ime
        - intellij-idea-ce
        - java
        - licecap
        - slack
        - slate
        - radiant-player
        - vagrant
        - virtualbox
    - name: register homebrew-installed zsh
      lineinfile:
        dest: /etc/shells
        line: /usr/local/bin/zsh
      become: true
    - name: chsh to zsh
      shell: chsh -s /usr/local/bin/zsh
      when: lookup('env', 'SHELL') != '/usr/local/bin/zsh'
    - name: set osx defaults
      command: defaults write -g {{ item }}
      with_items:
        - ApplePressAndHoldEnabled -bool false
        - KeyRepeat -int 2
        - com.apple.keyboard.fnState -int 1
        - com.apple.mouse.scaling -float 1.5
        - com.apple.scrollwheel.scaling -float 0.3125
        - com.apple.trackpad.scaling -float 1.5
        - com.apple.trackpad.scrolling -float 0.5
    - name: install karabiner private.xml
      shell: cp files/karabiner-private.xml ~/Library/Application\ Support/Karabiner/private.xml
    - name: configure karabiner
      command: /Applications/Karabiner.app/Contents/Library/bin/karabiner set {{ item.key }} {{ item.value }}
      with_dict:
        repeat.initial_wait: 200
        private.right_shift_to_hat_amp: 1
        private.ctrl_w_to_opt_delete: 1
        remap.simultaneouskeypresses_mouse_keys_mode_commandSD: 1
        option.emacsmode_controlLeftbracket: 1
        option.emacsmode_controlM: 1
        option.emacsmode_controlH: 1
        repeat.wait: 25
        option.mousekeys_mode_uio2click: 1
        parameter.mouse_key_scroll_natural_direction: 1
        option.emacsmode_controlPNBF: 1
    - name: install Java bundled fonts
      shell: cp -n "$(/usr/libexec/java_home)"/jre/lib/fonts/*.ttf /Library/Fonts/
      args:
        creates: /Library/Fonts/LucidaTypewriterRegular.ttf
